#ifndef MAINWINDOW_H                // Start of include guard to prevent multiple inclusions
#define MAINWINDOW_H                // Define the include guard macro

#include <QMainWindow>              // Include Qt's main window base class
#include <QTcpServer>               //It is used to wait for accept and client connection.
#include <QTcpSocket>              //It is provides TCP communication and used to connect the client application to serevr.
#include <QTableWidget>             // Include Qt class for displaying tabular data in the UI

QT_BEGIN_NAMESPACE                 // Begin Qt namespace block (used for compatibility with C++)
namespace Ui { class MainWindow; } // Forward declaration of the UI class generated by Qt Designer
QT_END_NAMESPACE                   // End Qt namespace block

class MainWindow : public QMainWindow // Declare MainWindow class inheriting from QMainWindow
{
    Q_OBJECT                          // Enable Qt's signal-slot mechanism for this class

public:
    explicit MainWindow(QWidget *parent = nullptr); // Constructor: initializes the main window with optional parent
    ~MainWindow();                                  // Destructor: cleans up resources

private slots:
    void newConnection();                          // Slot: triggered when a new client connects to the server
    void socketConnected();                        // Slot: triggered when the socket successfully connects
    void socketDisconnected();                     // Slot: triggered when the socket disconnects
    void socketReadyRead();                        // Slot: triggered when data is available to read from the socket
    void handleSocketError(QAbstractSocket::SocketError socketError); // Slot: triggered when a socket error occurs

    void on_tableWidget_cellActivated(int row, int column); // Slot: triggered when a table cell is activated (clicked or focused)

private:
    Ui::MainWindow *ui;             // Pointer to the UI object (auto-generated from .ui file)
    QTcpServer *server;             // TCP server object to listen for incoming connections
    QTcpSocket *clientSocket;       // TCP socket object to communicate with the connected client
    void setupTable();              // Helper: sets up the table widget (columns, headers, sorting)
    void insertRowToTable(const QStringList &fields); // Helper: inserts a row of data into the table
};
#endif // MAINWINDOW_H              // End of include guard

